name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "assets/**"
      - ".github/**/*.md"
  push:
    paths-ignore:
      - "README*.md"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
          cache: "gradle"

      - name: Create local.properties with SDK location
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check code style
        run: ./gradlew ktlintCheck --continue

      - name: Compile
        run: |
          ./gradlew assembleDebug
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk